// mobile/src/components/AutoGrowTextarea.vue
<template>
  <textarea
    ref="textareaEl"
    :value="modelValue"
    :rows="minRows"
    :style="{ maxHeight: `${maxHeight}px` }"
    @input="handleInput"
  ></textarea>
</template>

<script setup>
import { nextTick, onMounted, ref, watch } from 'vue'

const props = defineProps({
  modelValue: { type: String, default: '' },
  modelModifiers: { type: Object, default: () => ({}) },
  minRows: { type: Number, default: 1 },
  maxHeight: { type: Number, default: 150 },
})

const emit = defineEmits(['update:modelValue'])
const textareaEl = ref(null)

function resize() {
  const el = textareaEl.value
  if (!el) return
  el.style.height = 'auto'
  el.style.height = `${Math.min(el.scrollHeight, props.maxHeight)}px`
  el.style.overflowY = el.scrollHeight > props.maxHeight ? 'auto' : 'hidden'
}

function handleInput(event) {
  const nextValue = props.modelModifiers.trim ? event.target.value.trim() : event.target.value
  emit('update:modelValue', nextValue)
  nextTick(resize)
}

onMounted(resize)
watch(() => props.modelValue, () => nextTick(resize))
</script>

// client/src/components/AutoGrowTextarea.tsx
import { forwardRef, TextareaHTMLAttributes, useImperativeHandle, useLayoutEffect, useRef } from 'react';

type AutoGrowTextareaProps = TextareaHTMLAttributes<HTMLTextAreaElement> & {
  maxHeight?: number;
};

const AutoGrowTextarea = forwardRef<HTMLTextAreaElement, AutoGrowTextareaProps>(function AutoGrowTextarea(
  { maxHeight = 180, style, rows = 1, onChange, ...props },
  forwardedRef,
) {
  const ref = useRef<HTMLTextAreaElement>(null);
  useImperativeHandle(forwardedRef, () => ref.current as HTMLTextAreaElement);

  const resize = () => {
    const el = ref.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = `${Math.min(el.scrollHeight, maxHeight)}px`;
    el.style.overflowY = el.scrollHeight > maxHeight ? 'auto' : 'hidden';
  };

  useLayoutEffect(() => {
    resize();
  }, [props.value, maxHeight]);

  return (
    <textarea
      {...props}
      ref={ref}
      rows={rows}
      style={{ ...style, resize: 'none' }}
      onChange={event => {
        onChange?.(event);
        requestAnimationFrame(resize);
      }}
    />
  );
});

export default AutoGrowTextarea;
